- hosts: localhost
  tasks:
  - name: Wait until the Fortigate UI is available 
    ansible.builtin.uri:
      url: "https://{{ ansible_host }}:8443"        
      return_content: yes                                     # Return Http Response content
      validate_certs: no                                      # Not recommended, but a simple hack to avoid SSL checks
      status_code:                                            # List of HTTP status code considered to be as a successful request
        - 200
    register: website_health_check
    until: website_health_check.status                        # Wait until the HTTP code is 200
    retries: 20                                               # 20 * 10 seconds = 300s = 5 mins
    delay: 10                                                 # Every 10 seconds    

  - name: URL of the fortigate webserver
    ansible.builtin.debug:
      msg: "https://{{ansible_host}}:8443/"