---
- hosts: all
  become: yes
  tasks:
    - name: "Install the HTTPD Webserver"
      ansible.builtin.package:
        name: httpd
        state: present
    
    - name: "Start the HTTPD service"
      ansible.builtin.service:
        name: httpd
        state: started
        enabled: true

    
